
-- 1.	What is the average number of orders placed by customers per month?

SELECT CustomerID, COUNT(*) / COUNT(DISTINCT strftime('%Y-%m', PickupDateTime)) AS AvgOrdersPerMonth
FROM Orders
GROUP BY CustomerID;

-- 2. Which service type (e.g., laundry, ironing, dry cleaning) is most frequently requested?

SELECT ServiceName, COUNT(*) AS RequestCount
FROM Orders
JOIN Services ON Orders.ServiceID = Services.ServiceID
GROUP BY Orders.ServiceID
ORDER BY RequestCount DESC
LIMIT 1;

-- 3.	Which locations generate the highest number of orders?

SELECT 
L.AddressLine1,
COUNT(*) AS OrderCount
FROM 
Orders O
JOIN Locations L ON O.LocationID = L.LocationID
GROUP BY L.AddressLine1
ORDER BY OrderCount DESC
LIMIT 1;

-- 4.	What is the total revenue generated by services within a specific time period?

SELECT SUM(TotalAmount) AS TotalRevenue
FROM Orders
WHERE DeliveryDateTime BETWEEN '2024-01-01' AND '2024-01-31';

-- 5.	Which employees have completed the most assignments (e.g., pick-ups or deliveries) in the above used time period?

SELECT EA.EmployeeID, COUNT(*) AS AssignmentCount
FROM EmployeeAssignments EA
JOIN Orders O ON EA.OrderID = O.OrderID
WHERE O.DeliveryDateTime BETWEEN '2024-01-01' AND '2024-01-31'
GROUP BY EA.EmployeeID
ORDER BY AssignmentCount DESC;

-- 6.	What is the average delivery time for completed orders by location?

SELECT LocationID, AVG(julianday(DeliveryDateTime) - julianday(PickupDateTime)) AS AverageDeliveryHours 
FROM Orders 
WHERE OrderStatus = 'Delivered' 
GROUP BY LocationID;

-- 7.	What is the distribution of payment methods (e.g., credit card, cash) used by customers?

SELECT PaymentMethod, COUNT(*) AS MethodCount FROM Payments GROUP BY PaymentMethod;

-- 8.	How many customers placed repeat orders within a specified time frame?

SELECT COUNT(DISTINCT CustomerID) AS RepeatCustomers
FROM (
    SELECT CustomerID
    FROM Orders
    WHERE PickupDateTime BETWEEN '2024-01-01' AND '2024-01-31'
    GROUP BY CustomerID
    HAVING COUNT(*) > 1
);

-- 9.	What percentage of orders were delivered on time versus delayed?

SELECT
    SUM(CASE WHEN julianday(DeliveryDateTime) <= julianday(PickupDateTime, '+' || S.ServiceDuration || ' hours') THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS OnTimePercentage,
    SUM(CASE WHEN julianday(DeliveryDateTime) > julianday(PickupDateTime, '+' || S.ServiceDuration || ' hours') THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS DelayedPercentage
FROM 
    Orders O
JOIN 
    Services S ON O.ServiceID = S.ServiceID;

-- 10.	Are there underserved locations (low number of orders) where marketing efforts should be targeted?

SELECT LocationID, COUNT(*) AS OrderCount 
FROM Orders 
GROUP BY LocationID 
HAVING COUNT(*) <= (SELECT AVG(OrderCount) FROM (SELECT COUNT(*) AS OrderCount FROM Orders GROUP BY LocationID) AS SubQuery)
ORDER BY OrderCount;




